### ISSUE TITLE
Type annotations can only be used in TypeScript files

### ISSUE THREAD

**Issue by CodeMerchant** [Book-Microservices-v2/chapter04#1]
![cats](https://user-images.githubusercontent.com/51751028/134388742-7cd20201-a927-4907-9cad-8f60ef4d8cd9.jpg)
Having issues with the Promise interface as well as response and string, number data types. 
The error (as shown in the attached image) says _"Type annotations can only be used in Typescript files"_. How do I solve this? I keep getting a **_MethodArgumentNotValidException_** whenever I try to post an answer. Please assist if possible.

**Comment by mechero** [comment]
Looks like your IDE is not recognizing that file as TypeScript. You can try renaming it so the extension is `.ts`. If that doesn't work, try googling the error because it seems to be a pretty generic one. 

I hope this helps!

**Comment by CodeMerchant** [comment]
Ended up installing TypeScript globally. Changing the extension to .ts or .tsx seemed to break the js code so I reverted back to .js extensions. I still get the same red squiggly lines but the app now runs properly.

**Comment by mechero** [comment]
Great! Thanks for sharing the solution.
